# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  publish:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      TERM: dumb
    
    steps:
      - checkout
      - setup_remote_docker

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./scripts/circleci/sscontainer.sh build ping $CIRCLE_BUILD_NUM
      - run: ./scripts/circleci/sscontainer.sh test ping $CIRCLE_BUILD_NUM
      - run: ./scripts/circleci/sscontainer.sh publish ping $CIRCLE_BUILD_NUM

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      # TODO we should be running in a container with this pre installed
      - run: ./scripts/install-ecs-cli.sh linux
      - run: ./scripts/circleci/deploy.sh $CIRCLE_BUILD_NUM

workflows:
  version: 2
  publish_and_deploy:
    jobs:
      - publish
      - deploy:
          requires:
            - publish

