# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  publish:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      TERM: dumb
    
    steps:
      - checkout
      - setup_remote_docker
      - run: export VERSION=${CIRCLE_SHA1:0:7}
      - run: echo ${CIRCLE_SHA1:0:7}
      - run: echo $VERSION
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./scripts/circleci/sscontainer.sh build ping $VERSION
      - run: ./scripts/circleci/sscontainer.sh test ping $VERSION
      - run: ./scripts/circleci/sscontainer.sh publish ping $VERSION

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: export VERSION=$( eval ./scripts/circleci/buildversion.sh )
      # TODO we should be running in a container with this pre installed
      - run: ./scripts/install-ecs-cli.sh linux
      - run: ./scripts/circleci/deploy.sh $VERSION

workflows:
  version: 2
  publish_and_deploy:
    jobs:
      - publish
      - deploy:
          requires:
            - publish
