# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  publish:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      TERM: dumb
    
    steps:
      - checkout
      - setup_remote_docker
      # we unfortunetly can not export an env var. circleci issue.
      #   the reply here: https://discuss.circleci.com/t/how-to-set-env-vars-for-local-builds-using-circleci-2-0/12714
      #   would love to use scripts/circleci/buildversion.sh once we can.
      - run: echo "version ${CIRCLE_SHA1:0:7}"
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./scripts/circleci/sscontainer.sh build ping ${CIRCLE_SHA1:0:7}
      - run: ./scripts/circleci/sscontainer.sh test ping ${CIRCLE_SHA1:0:7}
      - run: ./scripts/circleci/sscontainer.sh publish ping ${CIRCLE_SHA1:0:7}

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: echo "version ${CIRCLE_SHA1:0:7}"
      # TODO we should be running in a container with this pre installed
      - run: ./scripts/install-ecs-cli.sh linux
      - run: ./scripts/circleci/deploy.sh ${CIRCLE_SHA1:0:7}

workflows:
  version: 2
  publish_and_deploy:
    jobs:
      - publish
      - deploy:
          requires:
            - publish
